//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRACTICA_3_YEISON_BERIGUETE
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public int PRODUCTOID { get; set; }
        public string NOMBREPRODUCTO { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal PRECIO { get; set; }
        public int Stock { get; set; }
        public Nullable<int> CATEGORIAID { get; set; }
    
        public virtual CATEGORIA CATEGORIA { get; set; }
    }
}
