//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRACTICA_3_YEISON_BERIGUETE
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDORE
    {
        public int PROVEEDORID { get; set; }
        public string NOMBREPROVEEDOR { get; set; }
        public string TELEFONO { get; set; }
        public string CORREOELECTRONIC { get; set; }
    }
}
